name: Gerar APK Android

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código
      uses: actions/checkout@v4

    - name: Configurar o Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Instalar o motor do Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.4'

    - name: Compilar o Aplicativo
      run: gradle assembleDebug

    - name: Salvar o APK pronto
      uses: actions/upload-artifact@v4
      with:
        name: Aplicativo-Topografia-APK
        path: app/build/outputs/apk/debug/app-debug.apk
